### ISSUE TITLE
Checking for suite requirements issue

### ISSUE THREAD

**Issue by RM83** [mbassalbioinformatics/ChIP-AP#1]
Hi,
First, thank you for developing ChIP-AP. I installed it on our University Cluster computer with the OS Red Hat Enterprise Linux 8. When I run the following command -
(python3_chipap) [xxx]$ ./chipap.py --mode single --ref hg38 --genome PATH/genomes --output PATH/output --setname xxx --sample_table PATH/xxx_samp_table.txt --custom_setting_table PATH/chip_ap_default_seetings_table.txt --fcmerge --goann --pathann --deltemp --thread 24 --run

The tool exits with the following messages -
Please make sure Genrich.py is installed, in PATH, and marked as executable
Please make sure fold_change_calculator.py is installed, in PATH, and marked as executable
Please make sure IDR_integrator.py is installed, in PATH, and marked as executable
Please make sure peak_caller_stats_calculator.py is installed, in PATH, and marked as executable
Please make sure GO_annotator.py is installed, in PATH, and marked as executable
Please make sure pathway_annotator.py is installed, in PATH, and marked as executable
Please make sure meme_sequence_extractor.py is installed, in PATH, and marked as executable

I confirm that these python programs are marked as executable. Also, chipap.py and these scripts are in the same directory. Could you please let me know what I did wrong here?

Thank you in advance.

**Comment by mbassalbioinformatics** [comment]
Have you checked that the scripts are included in your bashrc profile PATH? Its not enough that the scripts are marked executable, but need to be able to be called from any directory, hence the requirement for their export in your bashrc profile (or equivalent) as well.

**Comment by JSuryatenggara** [comment]
I'd also like to clarify that the path to directory where chipap.py etc scripts are located in your computer need to be registered in .bashrc file in your computer's home directory. 

This path is registered when you run the chipap_installer.py. If you, for example, moved all the scripts into another directory afterwards, then it won't work anymore.

You can check the registered path in your .bashrc file (e.g., with nano ~/.bashrc) and look for a line around the bottom of the file to see whether there is a registered path is where your scripts are. The line should look something like: PATH=$PATH:[path to your script directory here]

Please let me know if you need more help.

**Comment by RM83** [comment]
Thank you so much. I added the paths to bashrc. The tool is running well now.
