### ISSUE TITLE
[ASK] Filtering of Blacklisted Region

### ISSUE THREAD

**Issue by Shaylee-96** [mbassalbioinformatics/ChIP-AP#10]
Hi, may I know if ChIP-AP filters/removes blacklisted regions before peak calling?

**Comment by JSuryatenggara** [comment]
Hello Shaylee. Up to the latest version, ChIP-AP does not remove blacklisted regions.

**Comment by mbassalbioinformatics** [comment]
Hi Shaylee
as noted, chipap will not remove blacklisted regions in the current release. This is something we are considering adding in a future release (not for at least another 6-9 months unfortunately). 

For now what you can do however is manually exclude blacklisted regions. Following on from a [biostar question](https://www.biostars.org/p/184537/#211198), you can use the following command.
```
bedtools intersect -v -abam FILE.BAM -b BLACKLIST.BED > FILTERED.BAM
```
So what you can do is, generate the scripts for analysis using chipap, but just dont run the analysis. Next, go into the script following alignment and bam generation, write the command to filter out the bam files using the above command and save the script. Then when you run the chipap main script for the whole analysis, it will filter out the bam according to the command and if you write the command correctly, your filtered bam will be passed moving forward into all subsequent peak calling steps. Thus... filtered blacklisted bam files.

Hope that helps.
