### ISSUE TITLE
[REQUEST] Mapper based on read length

### ISSUE THREAD

**Issue by Ajeet1699** [mbassalbioinformatics/ChIP-AP#11]
Hi. I was trying to do peak calling by ChIP AP on a published data. Later on, I found that the AvgSpotLen for a datasest is too short (36). The aligner in this pipeline is 'bwa', which is great for >70bp. So, the mapped read percentage was very low for this particular datasets. 

I think assigning a mapper based on sequence read length in fastq will be a great help for analyzing the any published datasets (previous or new).

I have tried to use bowtie1 for my datasets with L>50, and it worked great.

**Comment by JSuryatenggara** [comment]
Hi, Ajeet. We tested a number of datasets with 36nt read length but haven't yet to come across a dataset where bwa mem struggled in mapping. So thank you so much for your report and suggestion. We will seriously consider having optional aligners in our next iteration.

Did you also try to process your dataset with bowtie2? I'm curious whether it works as well as bowtie1.

**Comment by JSuryatenggara** [comment]
I forgot to add that, for now, you can simply replace the 06_bwa_mem_aligning_script.sh in your output directory with your own script using bowtie. Or you can simply run bowtie individually  from the terminal for all your samples. Just need to make sure the output filenames matches the input filenames in the next script, which is the 07_MAPQ_filtering_script.sh. From there ChIP-AP can proceed with your dataset analysis.

**Comment by Ajeet1699** [comment]
Yes I am doing the same, aligning with bowtie1. Bowtie2 is also not suitable for short reads. 
I previously worked on multiple small RNA seq datasets, where I had found that bowtie2 is not performing better than bowtie1 for short reads.

**Comment by JSuryatenggara** [comment]
Duly noted. Thank you for trying that out.
