### ISSUE TITLE
[ASK] Can Chip-AP perform differential peak analysis? 

### ISSUE THREAD

**Issue by H1889** [mbassalbioinformatics/ChIP-AP#14]
Hi again, 
I have read chip-ap documentation and I am not sure if Chip-ap can perform differential peak analysis using bdgdiff or diffbind or something like that.
Best and thanks for the help

**Comment by mbassalbioinformatics** [comment]
Hi
are you referring to comparing 2 runs against each other to determine differential peaks? If I understand you correctly then no, ChIP-AP does not perform that at this time.

**Comment by H1889** [comment]
Yes, that is.
Thanks for the answer.
Best
