### ISSUE TITLE
[BUG] genomes.zip is an invalid zip file

### ISSUE THREAD

**Issue by lentaing** [mbassalbioinformatics/ChIP-AP#16]
**Describe the bug**
I've downloaded the genomes.zip file from the dropbox link several times and have gotten a error while extracting the file each time:
Archive:  genomes.zip
warning [genomes.zip]:  16401620869 extra bytes at beginning or within zipfile
  (attempting to process anyway)
error [genomes.zip]:  start of central directory not found;
  zipfile corrupt.

The md5 checksum of my file is 61ca6319bd37945b1c8a4092eab52586.  Can you confirm that this checksum is correct?

**To Reproduce**
1. $ wget https://www.dropbox.com/s/ioqd3hwdahh9xon/genomes.zip?e=1
2. $ unzip 'genomes.zip?e=1' #ERROR
3. $ mv 'genomes.zip?e=1' genomes.zip
4. $ unzip genomes.zip #ERROR

**Comment by mbassalbioinformatics** [comment]
GIve us a couple of days to split up the genomes.zip file into smaller fragments and upload again. It seems that downloading a large file is causing issues for yourself and others.

**Comment by lentaing** [comment]
Sure, no problem.  Thank you for the response!

**Comment by JSuryatenggara** [comment]
Hi,

thank you for waiting. I have uploaded the genomes in multiple parts. Here is the link to the folder:

https://www.dropbox.com/scl/fo/010598oidy0tf9bbt3an1/h?rlkey=lpu5mzx9zxlt3nar0eb06xmpn&dl=0

Extracting the archives should be pretty straightforward but, if necessary, please kindly follow the instructions in the read_me.txt file.

Don't hesitate to ask if you run into any problem.

Best regards,
Jeremiah Suryatenggara
Postdoctoral Researcher (Bioinformatics)
Daniel G Tenen Lab
Cancer Science Institute of Singapore
National University of Singapore
________________________________

**Comment by lentaing** [comment]
Thank you for the quick turn-around Jeremiah.  Would you also mind posting the md5 checksums so that I can be confident that the files I got on my end were not corrupted during transfer?

Thank you!

Regards,
Len

**Comment by JSuryatenggara** [comment]
Hello,

sorry for the delayed response. The md5sum is 61ca6319bd37945b1c8a4092eab52586.

How was your download? Was it corrupted?

Best regards,
Jeremiah Suryatenggara
Postdoctoral Researcher (Bioinformatics)
Daniel G Tenen Lab
Cancer Science Institute of Singapore
National University of Singapore
________________________________

**Comment by lentaing** [comment]
Hi Jeremiah,

I got it to work, thanks!  What I meant was md5-s for the different files in the multi-part zip, just so people can check to see if they need to redownload.  But my download worked!  Thanks again for your help!

Regards,
Len
