### ISSUE TITLE
[ASK]

### ISSUE THREAD

**Issue by ams134** [mbassalbioinformatics/ChIP-AP#18]
Are the blacklisted regions removed before peak calling or after? If they are removed before peak calling, is there a way to customise it as to not being removed before peak calling. As I am also interested in those blacklisted regions. A quick reply is appreciated.

**Comment by JSuryatenggara** [comment]
Hi, thanks for the question. Currently, ChIP-AP is not implementing the blacklisting process. An optional region blacklisting is currently in the list for further improvement in the future.

That means, at the moment, you can freely choose at which step you want to filter out the blacklisted regions (run the ChIP-AP generated scripts individually up to the step where you want to blacklist, perform the blacklisting, and then continue with the rest of the pipeline), or if you don't want to remove them at all (run ChIP-AP all the way to the end without interruption).

Hope this answers your question! Cheers!
