### ISSUE TITLE
[ASK] Can the pipeline run without control data?

### ISSUE THREAD

**Issue by h4rvey-g** [mbassalbioinformatics/ChIP-AP#6]
The ChIP-seq data I have does not contain control datasets. As far as I know, peak calling can proceed without control group. So can this pipeline run without control? If so, how should I edit the sample table file? Thanks.

**Comment by mbassalbioinformatics** [comment]
No, ChIP-AP does not run without a control dataset as a number of the calculations downstream require a control dataset. 

This decision was made early in development that we would not support such datasets since in our view, peaks cannot be called confidently or accurately, hence not supported.
