### ISSUE TITLE
The file "saccer3.chrom.sizes" should be named "sacCer3.chrom.sizes" [BUG]

### ISSUE THREAD

**Issue by shelkmike** [mbassalbioinformatics/ChIP-AP#8]
When ChIP-AP is used for Saccharomyces cerevisiae, an error happens:
`Please make sure GEM sacCer3 chromosome sizes reference file "sacCer3.chrom.sizes" exists`

To fix this, I had to rename "saccer3.chrom.sizes" to "sacCer3.chrom.sizes" both in the folder genomes/GEM and in the folder genomes/chrom.sizes

**Comment by JSuryatenggara** [comment]
Sorry to be replying so late. Thank you for the bug report! We will fix the "saccer3.chrom.sizes" file name in our upcoming genome folder upload.
