### ISSUE TITLE
[REQUEST] Ability to use custom genome

### ISSUE THREAD

**Issue by mohang13** [mbassalbioinformatics/ChIP-AP#9]
It is mentioned in the documentation that the ability to use custom genome will be added soon but I couldn't able to locate the tutorial for the same in the wiki. Please let me know how to add a custom genome for analysis.

**Comment by JSuryatenggara** [comment]
Hi Mohan, you can find the tutorial in the "Code" tab, inside the "Guides" folder, or can just click on the link below:
https://github.com/JSuryatenggara/ChIP-AP/blob/main/Guides/How%20to%20Generate%20Your%20Own%20ChIP-AP%20Genome%20Files.pdf

Please let me know if that did not solve your problem.
